# must accept EULA the first time that the image is started
# docker run splunk/enterprise:6.4.1-monitor
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/enterprise:6.4.1-monitor
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/enterprise:6.4.1-monitor 

version: '2'
services:
  vsplunk:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
  splunkenterprise:
 #   build: .
    hostname: splunkenterprise
    image: mchene/enterprise:6.4.3-monitor-gcp
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_USER: root
    volumes_from:
      - vsplunk
    ports:
      - "9000:8000"
      - "9997:9997"